#baseURL: "https://floridaman7588.me"
languageCode: "en-us"
title: "FloridaMan's Site"
theme: profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
disqusShortname: FloridaMan7588
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  title: "FloridaMan's Site"
  description: "FloridaMan7588's personal blog and website. Find information about projects, my personal life, or whatever I'm interested in at the moment."
  favicon: "Logo.png"
  useBootstrapCDN: false
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor: "#2f0147"
    secondaryTextColor: "#610f7f"
    backgroundColor: "#e2c2c6"
    secondaryBackgroundColor: "#e2c2c6"

    darkmode:
      textColor: "#e2c2c6"
      secondaryTextColor: "#b9929f"
      backgroundColor: "#2f0147"
      secondaryBackgroundColor: "#610f7f"


  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    showBrandLogo: false # Show brand logo in nav bar | default is true
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: true
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hello, I'm"
    title: "Cayden,"
    subtitle: "but you can call me FloridaMan."
    content: "I like to make things online, I'm not very good but I do it. I enjoy singing, system admin, and sometimes playing video games."
    image: Logo.png
    bottomImage:
      enable: true
      roundImage: true 
#    button:
#      enable: true
#      name: "Resume"
#      url: "#"
#      download: true
#      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github-alt
          url: https://fm7588.me/github
        - icon: fab fa-mastodon
          url: https://fm7588.me/mastodon
        - icon: fas fa-link
          url: "https://fm7588.me/littlelink"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
        Hi! I'm a 15 year old high school student who likes to make things online. I'm not very good at it, but I do it. I also enjoy singing, and sometimes playing video games. Sometimes I stream on YouTube, although I haven't uploaded there in a couple of years. I'll talk about my shenanigans here, and sometimes I write on Mastodon too.
    skills:
      enable: true
      title: "Some things I can kinda do"
      items:
        - "Web Design and HTML"
        - "(Cosplaying as a )\nSystems Administrator"
        - "Doing a little bit of code and stuff"
        - "Making 'quality' content"
        - "Maintaining Linux Apps"
        - "Maintaining docker-based projects"

  # Experience
  experience:
    enable: false
    # title: "Custom Name"
#    items:
#      - job: "Senior Software Developer"
#        company: "Facebook"
#        companyUrl: "https://example.com"
#        date: "Jan 2022 - present"
#        featuredLink:
#          enable: true
#          name: "View the project"
#          url: "https://example.com"
#        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."
#
#      - job: "Software Developer"
#        company: "Amazon"
#        companyUrl: "https://example.com"
#        date: "Sep 2020 - Dec 2021"
#        featuredLink:
#          enable: true
#          url: "https://example.com"
#        info:
#          enable: true
#          content: I worked as a software developer for more than one year in Amazon.
#        content: |
#          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
#
#          - Lead backend developer for a product.
#          - Created a frontend design for a product.
#
#      - job: "Junior Software Developer"
#        company: "Apple"
#        companyUrl: "https://example.com"
#        date: "Jan 2020 - Aug 2020"
#        info:
#          enable: false
#        featuredLink:
#          enable: true
#          url: "https://example.com"
#        content: |
#          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
#
#          - Lead backend developer for a product.
#          - Created a frontend design for a product.
#
#      - job: "UI/UX Designer"
#        company: "Netflix"
#        companyUrl: "https://example.com"
#        date: "June 2017 - Nov 2019"
#        featuredLink:
#          enable: true
#          url: "https://example.com"
#        content: |
#          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.
#
#          - Lead backend developer for a product.
#          - Created a frontend design for a product.
#
#      - job: "Product Designer"
#        company: "Google"
#        companyUrl: "https://example.com"
#        date: "Feb 2016 - Mar 2017"
#        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # Education
  education:
    enable: false
    # title: "Custom Name"
#    index: false
#    items:
#      - title: "Master of Business Administration"
#        school:
#          name: "University of California, Berkeley"
#          url: "https://example.org"
#        date: "2013 - 2015"
#        GPA: "3.8 out of 5.0"
#        content: |-
#          Extracurricular Activities
#            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
#            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
#      - title: "Bachelor of Science in Computer Science"
#        school:
#          name: "Massachusetts Institute of Technology"
#          url: "https://example.org"
#        date: "2009 - 2013"
#        GPA: "3.9 out of 5.0"
#        content: |-
#          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
#          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
#          - Face mask detection using a single convolutional neural network.
#
#          Extracurricular Activities
#            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
#            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
#        featuredLink:
#          enable: true
#          name: "My academic record"
#          url: "https://example.com"
#      - title: "High School"
#        school:
#          name: "Thomas Jefferson High School for Science and Technology."
#          url: "https://example.org"
#        GPA: "4.2 out of 5.0"
#        featuredLink:
#          enable: true
#          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
#    items:
#      - title: Google kickstart runner
#        content: I solved all problems with optimal solution.
#        url: https://example.com
#      - title: Facebook Hackathon Winner
#        content: Developed a product using Artificial Intelligence.
#      - title: Hugo Profile
#        content: Developed a theme and getting 1K+ downloads per month.
#        url: "https://github.com/gurusabarish/hugo-profile"
#      - title: Microsoft Imagine Runner
#        content: We are developed a product which can help others.
#      - title: Google Summer of Code
#        content: Contributed to a open source project.
#        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Waterfox As a Flatpak
        content: Waterfox, a browser built for the modern web, now available as a Flatpak.
        image: /images/projects/waterfox-logo.png
        featured:
          name: Download Here
          link: https://flathub.org/apps/net.waterfox.waterfox
        badges:
          - "Flatpak"
          - "Linux"
          - "Desktop"
        links:
          - icon: far fa-file-alt
            url: https://fm7588.me/waterfox-writeup
          - icon: fab fa-github-alt
            url: https://fm7588.me/waterfox-github

      - title: mochad-ha-addon
        content: A simple Home Assistant add-on for connecting X-10 ActiveHome devices to your smart home.
        image: /images/projects/mochad-logo.png
        featured:
          name: Get it Here!
          link: https://fm7588.me/ha-addons
        badges:
          - "Home Assistant"
          - "Linux"
          - "Docker"
        links:
          - icon: fab fa-github-alt
            url: https://fm7588.me/mochad-github

#      - title: Hugo Profile V2
#        content: A clean and simple Hugo template for personal portfolio and blog.
#        image: /images/projects/profile2.jpg
#        featured:
#          name: Demo V2
#          link: https://hugo-profile-2.netlify.app
#        badges:
#          - "Hugo"
#          - "Bootstrap"
#          - "Javascript"
#        links:
#          - icon: fab fa-github
#            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"
